service: 
    name: triggered-python-example
custom:
  bucket: test-bucket-for-csvs    
provider:
 name: aws
 runtime: python3.6
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.bucket}/*       

functions:
    indexItemCSV: 
        handler: handler.run
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: items/
              - suffix: .txt         
    indexCircEvent: 
        handler: circEventsImport.run
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: circEvents/
              - suffix: .csv                     

resources:
  Resources:
    CSVBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}  
      