service: 
    name: schedule-python-example
custom:
  bucket: test-bucket-for-csvs    
provider:
 name: aws
 runtime: python3.6
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.bucket}/* 

functions:
    getFilesViaSFTP: 
        handler: handler.run
        events:
         - schedule:
            rate: cron(0 14 * * ? *)
            enabled: true

resources:
  Resources:
    CSVBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}